### PR TITLE
Add download() and improve handling of temporary files

### PR DESCRIPTION
**Pull request by koheiw**
Adds `download()` with cache functionality. Unlike `quanteda.corpora::download()`, it only returns path the cache file, so that it can be used for all sorts of files.

### CODE REVIEW

**Comment by koheiw** [comment]
Let's merge this and update CRAN.

**Comment by kbenoit** [comment]
My main question is: Do we need this as a separate function? The nice thing about **readtext** is that is has a single function that works in a huge range of cases. Direct download from a remote is supposed to be one of those cases. With the news `cache` argument, repeated downloads do not need to be re-fetched from the remote. But do we then need a new exposed function (`download()`) for this? How about making this just work directly through `readtext()`?

Also the increasing complexity of the variety of ways that `readtext()` can be used points to the need for a vignette (https://github.com/quanteda/quanteda/issues/996 but really should be an issue for **readtext** and be added to a pkgdown site as per #61, #65).

Does this fix solve any other open issues, e.g. #119 or #105?

**Comment by koheiw** [comment]
I initially made it only accessible from `readtext` but I noticed that I want to download corpus objects. Since `readtext` always returns data.frame, this is inconsistent. This is why I separated it as `download()`.

I commented on #119 and #105 too.

**Comment by ogorodriguez** [comment]
Is the available already in readtext and/or quanteda?  Do I have update both packages?

**Pull request merged**
